### ISSUE TITLE
AWs needs ami retruned or possibly setting in Systems managet parameter store

### ISSUE THREAD

**Issue by jasonrichardsmith** [nanovms/ops#1229]
The only current way to reference an AMI on a CF stack is by awking ops output
```bash
ops image list -t aws -z eu-west-1 | awk 'NR==4' | cut -d '|' -f 2 | xargs
```
followed by an aws cli call to get the actual AMI ID (image name is useless with CF)

It would be good to just add the AMI ID to the output, since it already exists in the payload ops receives from AWS. Preferably in json, so it could be parsed with jq.

Alternately the AMI ID could be set on a "CloudConfig" SSM Parameter which can be referenced directly in Cloudformation templates.

```yaml
  AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/test/myimage'
```
This would require no parsing in DevOps pipelines.
