### ISSUE TITLE
Elasticsearch DB as a package

### ISSUE THREAD

**Issue by joshuaquek** [nanovms/ops#1333]
Hi @eyberg ! Joshua here! I saw the page on https://repo.ops.city/ that we are able to have databases as images (I saw that MongoDB, MySQL, Meilisearch are possible on the page). 
Is it possible to do the same with Elasticsearch DB?  

I am trying to figure this out by using a docker image https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html but havent had any success.

**Comment by eyberg** [comment]
yes, i know we've ran elastic before but i don't see a pkg for it so we could create one, your typical ELK stack would be {elastic,logstash,kibana} - both elastic && kibana would be their own packages while logstash could be a kllb and/or package depending on usage

**Comment by joshuaquek** [comment]
Hi Ian, awesome, yes this would be exactly it. For now I am trying to just do a simple Kibana unikernel and Elastic unikernel and to see if this works, but am running into issues. No worries, I will update my progress over here

**Comment by eyberg** [comment]
just an update on this i do have some pkgs that boot at but still need further work:

```
ops pkg load nanovms/elasticsearch:8.2.0 -p 9200 -p 9300
ops pkg load nanovms/kibana:8.2.2 -p 5601
```

however, the elastic one still needs quite a bit of configuration done to it as I think the rng and host lookup are off degrading perf - should definitely be fixable once we look into it more - it's probably just config; it's been a few years since i used kibana but I think you need to configure an es node to use it (if so can do that via config) - i put some notes into the readme and you can check the config like so:

```
➜  ~ cat ~/.ops/packages/nanovms/elasticsearch_8.2.0/package.manifest
{
  "Program":"/jdk/bin/java",
  "Version":"8.2.0",
  "Env": {
    "LD_PRELOAD": "l/l"
  },
  "BaseVolumeSz": "3g",
  "Env": {
    "JAVA_HOME": "/jdk",
    "LIBFFI_TMPDIR": "/tmp"
  },
  "RunConfig": {
    "Memory": "3G"
  },
  "Args": ["-Xshare:auto", "-Des.networkaddress.cache.ttl=60", "-Des.networkaddress.cache.negative.ttl=10",
  "-Djava.security.manager=allow", "-XX:+AlwaysPreTouch", "-Xss1m", "-Djava.awt.headless=true",
  "-Dfile.encoding=UTF-8", "-Djna.nosys=true", "-XX:-OmitStackTraceInFastThrow",
  "-XX:+ShowCodeDetailsInExceptionMessages", "-Dio.netty.noUnsafe=true",
  "-Dio.netty.noKeySetOptimization=true", "-Dio.netty.recycler.maxCapacityPerThread=0",
  "-Dlog4j.shutdownHookEnabled=false", "-Dlog4j2.disable.jmx=true", "-Dlog4j2.formatMsgNoLookups=true",
  "-Djava.locale.providers=SPI,COMPAT", "--add-opens=java.base/java.io=ALL-UNNAMED", "-XX:+UseG1GC",
  "-Djava.io.tmpdir=/tmp/elasticsearch-7184952636575940591", "-XX:+HeapDumpOnOutOfMemoryError",
  "-XX:+ExitOnOutOfMemoryError", "-XX:HeapDumpPath=data", "-XX:ErrorFile=/logs/hs_err_pid%p.log",
  "-Xlog:gc*,gc+age=trace,safepoint:file=/logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m",
  "-Xms1g", "-Xmx1g", "-XX:InitiatingHeapOccupancyPercent=30",
  "-XX:G1ReservePercent=25", "-Des.path.home=/",
  "-Dos.name=Linux",
  "-Des.path.conf=/config", "-Des.distribution.flavor=default",
  "-Des.distribution.type=tar", "-Des.bundled_jdk=true", "-cp", "/lib/*",
  "org.elasticsearch.bootstrap.Elasticsearch"
  ]
}
```

two main things I did w/es itself was to override the root check (we don't have users but some apps still want to check and we return a stub by default of '0', in this case I just made it 42), /proc/self/stat is also stubbed

**Comment by joshuaquek** [comment]
Hi @eyberg , thank you!! I have tried doing the `ops pkg load nanovms/elasticsearch:8.2.0 -p 9200 -p 9300` command, but it seems that its throwing me an error. 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/5335756/172013624-0cec4e22-e1cc-4e58-8627-87e52bd14aa7.png">

I have tried doing it with the official elasticsearch:8.2.2 docker image as I realise that you guys have the `from-docker` flag/command - https://nanovms.com/dev/tutorials/converting-docker-containers-to-nanos-unikernels , but to no avail

**Comment by joshuaquek** [comment]
Two weeks ago, I tried with a docker container, and after trying again, here was the same error that I got as that time:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/5335756/172013982-5e592721-63ba-4f15-a5d2-88439a1f5908.png">

...for Linux I believe that it is `bin/elasticsearch` or `elasticsearch.bat` for windows (https://www.elastic.co/downloads/elasticsearch#:~:text=2-,Start%20Elasticsearch,-Run%20bin/elasticsearch)

**Comment by joshuaquek** [comment]
I think the last time I tried this it was on an older version, Version 7.16 or 8.0, but for the old one as well as the latest one elasticsearch v8.2.2, both gave the same `not a dynamic executable` error

**Comment by joshuaquek** [comment]
On the bright side, I have tried running Kibana using your suggested command `ops pkg load nanovms/kibana:8.2.2 -p 5601` and it seems to start well! 👍🏼👍🏼 (screenshot below)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5335756/172015946-84a58c61-f708-4399-9a25-16466734e807.png">

I would then need to have a `kibana.yml` file which Kibana reads from. Usually this file can be edited at `/etc/kibana/kibana.yml` after installing Kibana from a tar.gz file. (Reference for `kibana.yml` that I am using as a guide - https://github.com/elastic/kibana/blob/main/config/kibana.yml )

<img width="290" alt="image" src="https://user-images.githubusercontent.com/5335756/172016408-ddd815aa-10a1-4661-ab50-bad958360e6e.png">

For my `config.json` I have structured it as such:
```json
{
  "Dirs": [],
  "CloudConfig": {
    "Platform": "aws",
    "ProjectID": "kibana-unikernel-demo",
    "Zone": "ap-southeast-1",
    "BucketName": "kibana-unikernel-demo-s3-bucket"
  },
  "Files": ["kibana.yml"],
  "RunConfig": {
    "Ports": ["5601"],
    "Verbose": true
  }
}
```

I am still in the midst of experimenting so get it working, and I will update my progress over here.
Thanks!

**Comment by joshuaquek** [comment]
Update: 

Kibana running on a unikernel works! I am testing this with an online Cloud-hosted Elasticsearch instance for now, as my local unikernel elasticsearch instance is not working as of yet.

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/5335756/172017892-8f2e3535-9db6-4eb2-972d-0ec2440411cb.png">

Latest `config.json` :
```json
{
  "Dirs": [],
  "CloudConfig": {
    "Platform": "aws",
    "ProjectID": "kibana-unikernel-demo",
    "Zone": "ap-southeast-1",
    "BucketName": "kibana-unikernel-demo-s3-bucket"
  },
  "Files": ["kibana.yml"],
  "Env": {
    "KBN_PATH_CONF": "/"
  },
  "RunConfig": {
    "Ports": ["5601"],
    "Verbose": true
  }
}
```

Directory Structure for Kibana specifiically:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/5335756/172017932-a7bf97f9-5c97-4ae3-8a00-374c26123cbe.png">

How my `kibana.yml` looks like (note that I had to generate the Service Account token using https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-service-token.html which then goes into the `kibana.yml` config) :
```yaml
# For more configuration options see the configuration guide for Kibana in
# https://www.elastic.co/guide/index.html

# =================== System: Kibana Server ===================
# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "0.0.0.0"

# Enables you to specify a path to mount Kibana at if you are running behind a proxy.
# Use the `server.rewriteBasePath` setting to tell Kibana if it should remove the basePath
# from requests it receives, and to prevent a deprecation warning at startup.
# This setting cannot end in a slash.
#server.basePath: ""

# Specifies whether Kibana should rewrite requests that are prefixed with
# `server.basePath` or require that they are rewritten by your reverse proxy.
# Defaults to `false`.
#server.rewriteBasePath: false

# Specifies the public URL at which Kibana is available for end users. If
# `server.basePath` is configured this URL should end with the same basePath.
server.publicBaseUrl: "http://0.0.0.0:5601"

# The maximum payload size in bytes for incoming server requests.
#server.maxPayload: 1048576

# The Kibana server's name. This is used for display purposes.
server.name: "kibana-unikernel"

# =================== System: Kibana Server (Optional) ===================
# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
#server.ssl.enabled: false
#server.ssl.certificate: /path/to/your/server.crt
#server.ssl.key: /path/to/your/server.key

# =================== System: Elasticsearch ===================
# The URLs of the Elasticsearch instances to use for all your queries.
elasticsearch.hosts: ["https://sample.my-cluster-address.com:9243"]

# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the Kibana
# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
# elasticsearch.username: "default"
# elasticsearch.password: "default"

# Kibana can also authenticate to Elasticsearch via "service account tokens".
# Service account tokens are Bearer style tokens that replace the traditional username/password based configuration.
# Use this token instead of a username/password.
elasticsearch.serviceAccountToken: "Please generate via https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-service-token.html. Then paste the generated token here."

# Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
# the elasticsearch.requestTimeout setting.
#elasticsearch.pingTimeout: 1500

# Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
# must be a positive integer.
#elasticsearch.requestTimeout: 30000

# The maximum number of sockets that can be used for communications with elasticsearch.
# Defaults to `Infinity`.
#elasticsearch.maxSockets: 1024

# Specifies whether Kibana should use compression for communications with elasticsearch
# Defaults to `false`.
#elasticsearch.compression: false

# List of Kibana client-side headers to send to Elasticsearch. To send *no* client-side
# headers, set this value to [] (an empty list).
#elasticsearch.requestHeadersWhitelist: [ authorization ]

# Header names and values that are sent to Elasticsearch. Any custom headers cannot be overwritten
# by client-side headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
#elasticsearch.customHeaders: {}

# Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
#elasticsearch.shardTimeout: 30000

# =================== System: Elasticsearch (Optional) ===================
# These files are used to verify the identity of Kibana to Elasticsearch and are required when
# xpack.security.http.ssl.client_authentication in Elasticsearch is set to required.
#elasticsearch.ssl.certificate: /path/to/your/client.crt
#elasticsearch.ssl.key: /path/to/your/client.key

# Enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
#elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
#elasticsearch.ssl.verificationMode: full

# =================== System: Logging ===================
# Set the value of this setting to off to suppress all logging output, or to debug to log everything. Defaults to 'info'
#logging.root.level: debug

# Enables you to specify a file where Kibana stores log output.
#logging.appenders.default:
#  type: file
#  fileName: /var/logs/kibana.log
#  layout:
#    type: json

# Logs queries sent to Elasticsearch.
#logging.loggers:
#  - name: elasticsearch.query
#    level: debug

# Logs http responses.
#logging.loggers:
#  - name: http.server.response
#    level: debug

# Logs system usage information.
#logging.loggers:
#  - name: metrics.ops
#    level: debug

# =================== System: Other ===================
# The path where Kibana stores persistent data not saved in Elasticsearch. Defaults to data
#path.data: data

# Specifies the path where Kibana creates the process ID file.
#pid.file: /run/kibana/kibana.pid

# Set the interval in milliseconds to sample system and process performance
# metrics. Minimum is 100ms. Defaults to 5000ms.
#ops.interval: 5000

# Specifies locale to be used for all localizable strings, dates and number formats.
# Supported languages are the following: English (default) "en", Chinese "zh-CN", Japanese "ja-JP", French "fr-FR".
#i18n.locale: "en"

# =================== Frequently used (Optional)===================

# =================== Saved Objects: Migrations ===================
# Saved object migrations run at startup. If you run into migration-related issues, you might need to adjust these settings.

# The number of documents migrated at a time.
# If Kibana can't start up or upgrade due to an Elasticsearch `circuit_breaking_exception`,
# use a smaller batchSize value to reduce the memory pressure. Defaults to 1000 objects per batch.
#migrations.batchSize: 1000

# The maximum payload size for indexing batches of upgraded saved objects.
# To avoid migrations failing due to a 413 Request Entity Too Large response from Elasticsearch.
# This value should be lower than or equal to your Elasticsearch cluster’s `http.max_content_length`
# configuration option. Default: 100mb
#migrations.maxBatchSizeBytes: 100mb

# The number of times to retry temporary migration failures. Increase the setting
# if migrations fail frequently with a message such as `Unable to complete the [...] step after
# 15 attempts, terminating`. Defaults to 15
migrations.retryAttempts: 2

# =================== Search Autocomplete ===================
# Time in milliseconds to wait for autocomplete suggestions from Elasticsearch.
# This value must be a whole number greater than zero. Defaults to 1000ms
#unifiedSearch.autocomplete.valueSuggestions.timeout: 1000

# Maximum number of documents loaded by each shard to generate autocomplete suggestions.
# This value must be a whole number greater than zero. Defaults to 100_000
#unifiedSearch.autocomplete.valueSuggestions.terminateAfter: 100000
```
